In [2]:
import numpy as np

# 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print(f"Shape: {arr1d.shape}") # Shape: (5,)
print(f"Dimensions: {arr1d.ndim}") # Dimensions: 1

# 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Shape: {arr2d.shape}") # Shape: (2, 3)
print(f"Dimensions: {arr2d.ndim}") # Dimensions: 2

# 3D array
arr3d = np.zeros((2, 3, 4))
print(f"Shape: {arr3d.shape}") # Shape: (2, 3, 4)
print(f"Total elements: {arr3d.size}") # Total elements: 24

Shape: (5,)
Dimensions: 1
Shape: (2, 3)
Dimensions: 2
Shape: (2, 3, 4)
Total elements: 24


In [3]:
# Specify data type during creation
int_arr = np.array([1, 2, 3], dtype=np.int32)
float_arr = np.array([1.0, 2.0, 3.0], dtype=np.float32)
bool_arr = np.array([True, False, True], dtype=bool)

print(f"Integer array: {int_arr.dtype}") # int32
print(f"Float array: {float_arr.dtype}") # float32
print(f"Boolean array: {bool_arr.dtype}") # bool

# Convert between types
original = np.array([1.7, 2.3, 3.9])
as_int = original.astype(np.int32)
print(f"Original: {original}") # [1.7 2.3 3.9]
print(f"As integer: {as_int}") # [1 2 3]

# Memory usage comparison
print(f"Float64 memory: {np.array([1.0]).nbytes} bytes") # 8 bytes
print(f"Float32 memory: {np.array([1.0], dtype=np.float32).nbytes} bytes") # 4 bytes

Integer array: int32
Float array: float32
Boolean array: bool
Original: [1.7 2.3 3.9]
As integer: [1 2 3]
Float64 memory: 8 bytes
Float32 memory: 4 bytes


In [4]:
# 2D array with shape (3, 4)
arr = np.arange(12).reshape(3, 4)
print("Array:")
print(arr)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

print(f"Shape: {arr.shape}")        # (3, 4)
print(f"Strides: {arr.strides}")    # (32, 8) on 64-bit system
print(f"Item size: {arr.itemsize}") # 8 bytes (int64)

# Understanding strides:
# - Moving to next row: skip 32 bytes (4 elements × 8 bytes)
# - Moving to next column: skip 8 bytes (1 element × 8 bytes)

Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)
Strides: (32, 8)
Item size: 8


In [5]:
# Start with 1D array
original = np.arange(12)
print(f"Original: {original}") # [0 1 2 3 4 5 6 7 8 9 10 11]
print(f"Shape: {original.shape}") # (12,)

# Reshape to 2D
matrix = original.reshape(3, 4)
print(f"3x4 matrix:\n{matrix}")
# [[ 0 1 2 3]
# [ 4 5 6 7]
# [ 8 9 10 11]]

# Reshape to 3D
tensor = original.reshape(2, 2, 3)
print(f"2x2x3 tensor shape: {tensor.shape}")

# Use -1 for automatic dimension calculation
auto_shape = original.reshape(-1, 2) # NumPy calculates: (6, 2)
print(f"Auto-calculated shape: {auto_shape.shape}")

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)
3x4 matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2x2x3 tensor shape: (2, 2, 3)
Auto-calculated shape: (6, 2)


In [6]:
original = np.array([[1, 2, 3], [4, 5, 6]])

# Creating a view (shares memory)
view = original[0:2, 0:2] # Slice creates a view
view[0, 0] = 999
print(f"Original after view change:\n{original}")
# [[999 2 3]
# [ 4 5 6]]

# Creating a copy (independent memory)
copy = original.copy()
copy[0, 0] = 777
print(f"Original after copy change:\n{original}") # Unchanged

Original after view change:
[[999   2   3]
 [  4   5   6]]
Original after copy change:
[[999   2   3]
 [  4   5   6]]


In [7]:
arr = np.random.randint(0, 100, size=(4, 5)).astype(np.float32)

# Essential array properties
print(f"Shape: {arr.shape}") # Dimensions
print(f"Data type: {arr.dtype}") # Element type
print(f"Size: {arr.size}") # Total elements
print(f"Item size: {arr.itemsize}") # Bytes per element
print(f"Total bytes: {arr.nbytes}") # Total memory usage
print(f"Dimensions: {arr.ndim}") # Number of axes

# Memory layout information
print(f"C-contiguous: {arr.flags.c_contiguous}")
print(f"F-contiguous: {arr.flags.f_contiguous}")
print(f"Strides: {arr.strides}")

# Quick data preview
print(f"Min value: {arr.min()}")
print(f"Max value: {arr.max()}")
print(f"Mean: {arr.mean():.2f}")

Shape: (4, 5)
Data type: float32
Size: 20
Item size: 4
Total bytes: 80
Dimensions: 2
C-contiguous: True
F-contiguous: False
Strides: (20, 4)
Min value: 0.0
Max value: 94.0
Mean: 49.80


In [8]:
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
row_indices = [0, 2]
col_indices = [1, 0]
result = arr_2d[row_indices, col_indices]
print(result)  # [2 5]

[2 5]


In [9]:
# Combine boolean and fancy indexing
data = np.random.randint(0, 100, (5, 4))
print("Original data:")
print(data)

# Select rows where first column > 50
mask = data[:, 0] > 50
selected_rows = data[mask]
print("\nRows where first column > 50:")
print(selected_rows)

# Select specific columns from these rows
columns_to_select = [1, 3]
final_result = selected_rows[:, columns_to_select]
print("\nColumns 1 and 3 from selected rows:")
print(final_result)

Original data:
[[56 26 55 83]
 [38 56 66 97]
 [34 46 12 89]
 [26 67 86 10]
 [68 79 92 82]]

Rows where first column > 50:
[[56 26 55 83]
 [68 79 92 82]]

Columns 1 and 3 from selected rows:
[[26 83]
 [79 82]]


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6])
print("Original shape:", arr.shape)  # (6,)

# Reshape to 2D
arr_2d = arr.reshape(2, 3)
print("2x3 shape:")
print(arr_2d)
# [[1 2 3]
#  [4 5 6]]

# Reshape to 3D
arr_3d = arr.reshape(2, 1, 3)
print("3D shape:", arr_3d.shape)  # (2, 1, 3)

Original shape: (6,)
2x3 shape:
[[1 2 3]
 [4 5 6]]
3D shape: (2, 1, 3)


In [15]:
arr = np.array([[1, 2], [3, 4]])
flat = arr.flatten()
flat[0] = 99
print(arr[0, 0])  # Still 1 (copy)
print(flat)

1
[99  2  3  4]


In [17]:
arr = np.array([[1, 2], [3, 4]])
rav = arr.ravel()
rav[0] = 99
print(arr[0, 0])  # Now 99 (view)
print(arr)
print(rav)

99
[[99  2]
 [ 3  4]]
[99  2  3  4]


In [18]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Original shape:", arr.shape)  # (2, 3)

# Transpose methods
transposed = arr.T
# or arr.transpose()
print("Transposed shape:", transposed.shape)  # (3, 2)
print(transposed)
# [[1 4]
#  [2 5]
#  [3 6]]

Original shape: (2, 3)
Transposed shape: (3, 2)
[[1 4]
 [2 5]
 [3 6]]


In [19]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
result = arr + 10
print(result)
# [[11 12 13]
#  [14 15 16]]

# Shape compatibility:
# (2, 3) + () → (2, 3)

[[11 12 13]
 [14 15 16]]


In [20]:
arr = np.array([[1, 2, 3],
 [4, 5, 6]])
col_vector = np.array([[10], [20]])
result = arr + col_vector
print(result)
# [[11 12 13]
# [24 25 26]]

# Shape compatibility:
# (2, 3) + (2, 1) → (2, 3)

[[11 12 13]
 [24 25 26]]


In [24]:
# Broadcasting with different dimensional arrays
arr_2d = np.array([[1, 2, 3],
 [4, 5, 6]]) # Shape: (2, 3)
arr_1d = np.array([10, 20, 30]) # Shape: (3,)

print(arr_1d)
print(arr_2d)

result = arr_2d + arr_1d
print("2D + 1D result:")
print(result)
# [[11 22 33]
# [14 25 36]]

# 3D broadcasting example
arr_3d = np.random.random((2, 3, 4)) # Shape: (2, 3, 4)
arr_2d = np.random.random((3, 1)) # Shape: (3, 1)
result_3d = arr_3d + arr_2d # Shape: (2, 3, 4)

[10 20 30]
[[1 2 3]
 [4 5 6]]
2D + 1D result:
[[11 22 33]
 [14 25 36]]


In [30]:
data = np.random.random((1000, 5))
mean = data.mean(axis=0)  # Shape: (5,)
std = data.std(axis=0)    # Shape: (5,)
normalized = (data - mean) / std
print(data)
print(mean)
print(std)
print(normalized)

[[0.98300592 0.79170937 0.55375566 0.21835576 0.44253571]
 [0.73372535 0.83366011 0.15090624 0.97039769 0.99326417]
 [0.75629196 0.17735186 0.36167232 0.13603165 0.00743921]
 ...
 [0.88838894 0.44560818 0.82893205 0.64650533 0.80648965]
 [0.78487668 0.79064601 0.44859511 0.49029936 0.04792341]
 [0.9384643  0.64588957 0.5007478  0.06377713 0.0319691 ]]
[0.49126217 0.50662321 0.48599876 0.50558629 0.5018489 ]
[0.29463419 0.29561515 0.28942952 0.28575896 0.29503557]
[[ 1.66899761  0.96438278  0.23410501 -1.00514966 -0.20103741]
 [ 0.82292954  1.10629279 -1.15776895  1.62658556  1.66561364]
 [ 0.89952151 -1.11385141 -0.42955687 -1.29323903 -1.67576297]
 ...
 [ 1.34786383 -0.20640021  1.1848594   0.49313952  1.03255601]
 [ 0.99653916  0.96078568 -0.12923231 -0.05349588 -1.53854497]
 [ 1.51782159  0.47110701  0.05095902 -1.54609032 -1.59262085]]


In [35]:
matrix = np.random.random((10, 10))
row_sums = matrix.sum(axis=1, keepdims=True)
probabilities = matrix / row_sums # Normalize rows

print('Matrix')
print(matrix)
print('Row sums')
print(row_sums)
print('Probabilities')
print(probabilities)

Matrix
[[0.32069393 0.98176335 0.14224038 0.28314197 0.87946677 0.46635728
  0.76254522 0.54684942 0.67928486 0.29168965]
 [0.50517143 0.90798089 0.92509442 0.50931089 0.1190659  0.96311221
  0.16503944 0.29074389 0.17259213 0.87253782]
 [0.24819376 0.66487524 0.13862676 0.2943477  0.69188943 0.98247432
  0.06987879 0.95989997 0.12290277 0.85949805]
 [0.34223231 0.13710306 0.59359573 0.10355045 0.07789671 0.91823496
  0.95240619 0.97099243 0.60646738 0.21255643]
 [0.90848991 0.59425483 0.50390957 0.28135093 0.6691841  0.79317922
  0.4323999  0.63016591 0.54117295 0.45769866]
 [0.89811028 0.56423283 0.53030897 0.92340744 0.54094515 0.56577242
  0.67243288 0.0127325  0.50015873 0.86300429]
 [0.17513039 0.70382705 0.99759747 0.11781657 0.63035958 0.70520126
  0.26046134 0.54923556 0.15766205 0.23135005]
 [0.47294254 0.64503513 0.74758073 0.86308856 0.19777993 0.91194749
  0.32095926 0.31918792 0.77739906 0.18521047]
 [0.82210476 0.35780202 0.10174157 0.53097118 0.65066833 0.45459264
  0.0