In [2]:
import numpy as np

# 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print(f"Shape: {arr1d.shape}") # Shape: (5,)
print(f"Dimensions: {arr1d.ndim}") # Dimensions: 1

# 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Shape: {arr2d.shape}") # Shape: (2, 3)
print(f"Dimensions: {arr2d.ndim}") # Dimensions: 2

# 3D array
arr3d = np.zeros((2, 3, 4))
print(f"Shape: {arr3d.shape}") # Shape: (2, 3, 4)
print(f"Total elements: {arr3d.size}") # Total elements: 24

Shape: (5,)
Dimensions: 1
Shape: (2, 3)
Dimensions: 2
Shape: (2, 3, 4)
Total elements: 24


In [3]:
# Specify data type during creation
int_arr = np.array([1, 2, 3], dtype=np.int32)
float_arr = np.array([1.0, 2.0, 3.0], dtype=np.float32)
bool_arr = np.array([True, False, True], dtype=bool)

print(f"Integer array: {int_arr.dtype}") # int32
print(f"Float array: {float_arr.dtype}") # float32
print(f"Boolean array: {bool_arr.dtype}") # bool

# Convert between types
original = np.array([1.7, 2.3, 3.9])
as_int = original.astype(np.int32)
print(f"Original: {original}") # [1.7 2.3 3.9]
print(f"As integer: {as_int}") # [1 2 3]

# Memory usage comparison
print(f"Float64 memory: {np.array([1.0]).nbytes} bytes") # 8 bytes
print(f"Float32 memory: {np.array([1.0], dtype=np.float32).nbytes} bytes") # 4 bytes

Integer array: int32
Float array: float32
Boolean array: bool
Original: [1.7 2.3 3.9]
As integer: [1 2 3]
Float64 memory: 8 bytes
Float32 memory: 4 bytes


In [4]:
# 2D array with shape (3, 4)
arr = np.arange(12).reshape(3, 4)
print("Array:")
print(arr)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

print(f"Shape: {arr.shape}")        # (3, 4)
print(f"Strides: {arr.strides}")    # (32, 8) on 64-bit system
print(f"Item size: {arr.itemsize}") # 8 bytes (int64)

# Understanding strides:
# - Moving to next row: skip 32 bytes (4 elements × 8 bytes)
# - Moving to next column: skip 8 bytes (1 element × 8 bytes)

Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)
Strides: (32, 8)
Item size: 8


In [5]:
# Start with 1D array
original = np.arange(12)
print(f"Original: {original}") # [0 1 2 3 4 5 6 7 8 9 10 11]
print(f"Shape: {original.shape}") # (12,)

# Reshape to 2D
matrix = original.reshape(3, 4)
print(f"3x4 matrix:\n{matrix}")
# [[ 0 1 2 3]
# [ 4 5 6 7]
# [ 8 9 10 11]]

# Reshape to 3D
tensor = original.reshape(2, 2, 3)
print(f"2x2x3 tensor shape: {tensor.shape}")

# Use -1 for automatic dimension calculation
auto_shape = original.reshape(-1, 2) # NumPy calculates: (6, 2)
print(f"Auto-calculated shape: {auto_shape.shape}")

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)
3x4 matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2x2x3 tensor shape: (2, 2, 3)
Auto-calculated shape: (6, 2)


In [6]:
original = np.array([[1, 2, 3], [4, 5, 6]])

# Creating a view (shares memory)
view = original[0:2, 0:2] # Slice creates a view
view[0, 0] = 999
print(f"Original after view change:\n{original}")
# [[999 2 3]
# [ 4 5 6]]

# Creating a copy (independent memory)
copy = original.copy()
copy[0, 0] = 777
print(f"Original after copy change:\n{original}") # Unchanged

Original after view change:
[[999   2   3]
 [  4   5   6]]
Original after copy change:
[[999   2   3]
 [  4   5   6]]


In [7]:
arr = np.random.randint(0, 100, size=(4, 5)).astype(np.float32)

# Essential array properties
print(f"Shape: {arr.shape}") # Dimensions
print(f"Data type: {arr.dtype}") # Element type
print(f"Size: {arr.size}") # Total elements
print(f"Item size: {arr.itemsize}") # Bytes per element
print(f"Total bytes: {arr.nbytes}") # Total memory usage
print(f"Dimensions: {arr.ndim}") # Number of axes

# Memory layout information
print(f"C-contiguous: {arr.flags.c_contiguous}")
print(f"F-contiguous: {arr.flags.f_contiguous}")
print(f"Strides: {arr.strides}")

# Quick data preview
print(f"Min value: {arr.min()}")
print(f"Max value: {arr.max()}")
print(f"Mean: {arr.mean():.2f}")

Shape: (4, 5)
Data type: float32
Size: 20
Item size: 4
Total bytes: 80
Dimensions: 2
C-contiguous: True
F-contiguous: False
Strides: (20, 4)
Min value: 2.0
Max value: 93.0
Mean: 56.25


In [8]:
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
row_indices = [0, 2]
col_indices = [1, 0]
result = arr_2d[row_indices, col_indices]
print(result)  # [2 5]

[2 5]
